### ISSUE TITLE
Упрощение кода

### ISSUE THREAD

**Issue by ivzherebtsov** [FlexxxerAlex/TXT_FrameTimeHandler#2]
Предлагаю немного упростить код:
**метод** `ProcessFrameViewFile(string path)` **в файле** _FrameViewDataProcessing.cs_ и `ProcessFrapsFile(string path)`  _FrapsDataProcessing.cs_

```C#
try {
    ...
    return new Maybe<FramesData>( new FramesData( framesTimes )  ); 
}
catch (Exception)
{
    return Maybe<FramesData>.None;
}
finally 
{
    if (fs != null) fs.Dispose();
    if (bs != null) bs.Dispose();
    if (sr != null) sr.Dispose();
}
```
Для того, чтобы:
1 -убрать лишние проверки на null (они будут выполнены в любом случае, т.к. находятся в блоке finally)
2 - упростить код и, возможно, немного ускорить выполнение
Метод вернет:
ОШИБОК НЕТ: ``` Maybe<FramesData>( new FramesData( framesTimes)  )```
ОШИБКИ ЕСТЬ: ``` Maybe<FramesData>.None```

Затем будут вызваны Dispose у не null-переменных
если ошибки нет, сначала вызовет Dispose у не null-переменных, а затем вернет

**Comment by flexxxxer** [comment]
Fixed with commit dee2b817ac6cf62dd8c28cf8cbad9c4e26bd7709
