### ISSUE TITLE
Указание имени и подгрузка файла с логами

### ISSUE THREAD

**Issue by ivzherebtsov** [FlexxxerAlex/TXT_FrameTimeHandler#4]
в ролике "Этот компьютер" есть проблема с тем, что постоянно Павел? забывал изменить имя теста

не будет лучше спросить название при выборе логов и отобразить его в заголовке окна?
Алгоритм примерно такой:
Выбрали файл с логами, написали название "WD2 test 1...", обработали данные из файла, сохранили результаты в data.txt, в заголовке отобразили "WD2 test 1..." 

Пользователь поймет, что он работает с WD2 test 1

Захочет обработать еще тест: пусть выберет лог-файл, введет название "WD2 test 2 ..." ну и т.д?

условный "проект" - создается/получается при выборе файла с логами?

**Comment by flexxxxer** [comment]
Есть идея получше, предложенная Павлом: после ввода имени теста и нажатии кнопки "обзор", с последующим выбором, блокировать кнопку выбора файла до тех пор, пока человек не ведёт новое имя теста

UPD: да, "проект" генерируется при выборе файла с логами
