### ISSUE TITLE
Тёмная тема

### ISSUE THREAD

**Issue by 73794449** [FlexxxerAlex/TXT_FrameTimeHandler#7]
Я предлагаю сделать кнопку(или клик по заголовку окна) в результате которого включается тёмный режим, но многие предпочитают повышеную контрасность данного режима. Как реализовать переключение тем и нужно ли это вообще?

**Comment by flexxxxer** [comment]
Реализация тем напрямую зависит от программиста. По-хорошему реализация хорошего theme-provider с сомвестимостью dependency property для xaml - задача не из простых, и ее решение не повысит эффективность работы в программе.

Нужно или нет? **По-моему мнению**   нет
Сложно ли это реализовать? **Зависит**
**Пока что** я не вижу смысла реализовывать эту функциональность

**Comment by 73794449** [comment]
Ок, тёмная тема пока откладывается
